# Generated by Django 5.1.2 on 2024-11-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_options_alter_mailing_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='filter',
            new_name='filters',
        ),
    ]
