version: '3.7'

services:

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.25.0-alpine
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - web
  
  celery:
    build: .
    command: bash -c "celery -A mailing_service worker --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery-beat:
    build: .
    command: bash -c "celery -A mailing_service beat --loglevel=info"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
